{
    "openapi": "3.0.0",
    "info": {
        "title": "PPM API",
        "contact": {},
        "version": "1.0"
    },
    "servers": [
        {
            "url": "http://127.0.0.1:4000",
            "variables": {}
        }
    ],
    "paths": {
        "/patients": {
            "get": {
                "tags": ["Patients"],
                "summary": "List all patients.",
                "operationId": "list_all_patinets",
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false,
                "security": [
                    {
                        "bearer": []
                    }
                ]
            },
            "post": {
                "tags": ["Patients"],
                "summary": "Add new patient",
                "operationId": "add_patient",
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "allOf": [
                                    {
                                        "$ref": "#/components/schemas/AddPatientRequest"
                                    }
                                ]
                            },
                            "example": {
                                "full_name": "Ram Lakhan",
                                "email": "ak00313@gmail.com",
                                "phone": "9863180880",
                                "address": "Kathmandu",
                                "date_of_birth": "2022-11-01",
                                "is_special_attention": true,
                                "avatar_filename": "xxx.jpg"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    },
                    "400": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false,
                "security": [
                    {
                        "bearer": []
                    }
                ]
            }
        },
        "/patients/{id}": {
            "get": {
                "tags": ["Patients"],
                "summary": "Get patient detail.",
                "operationId": "getUserPartialResults.",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID of patient",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int32"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false,
                "security": [
                    {
                        "bearer": []
                    }
                ]
            },
            "put": {
                "tags": ["Patients"],
                "summary": "Update patient",
                "operationId": "update_patient",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID of patient",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int32"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "allOf": [
                                    {
                                        "$ref": "#/components/schemas/UpdatePatientRequest"
                                    },
                                    {
                                        "example": {
                                            "full_name": "Ram Lakhan",
                                            "email": "ak00313@gmail.com",
                                            "phone": "9863180880",
                                            "address": "Kathmandu",
                                            "date_of_birth": "2022-11-01",
                                            "is_special_attention": true,
                                            "avatar_filename": "xxx.jpg"
                                        }
                                    }
                                ]
                            },
                            "example": {
                                "full_name": "Ram Lakhan",
                                "email": "ak00313@gmail.com",
                                "phone": "9863180880",
                                "address": "Kathmandu",
                                "date_of_birth": "2022-11-01",
                                "is_special_attention": true,
                                "avatar_filename": "xxx.jpg"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false,
                "security": [
                    {
                        "bearer": []
                    }
                ]
            },
            "delete": {
                "tags": ["Patients"],
                "description": "deletes a patient",
                "operationId": "delete_patient",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID of patient to delete",
                        "required": true,
                        "type": "integer",
                        "format": "int64"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Patient deleted"
                    },
                    "default": {
                        "description": "unexpected error"
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "tags": ["Authentication"],
                "summary": "Signup API",
                "operationId": "SignupAPI",
                "parameters": [],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "allOf": [
                                    {
                                        "$ref": "#/components/schemas/SignupAPIRequest"
                                    },
                                    {
                                        "example": {
                                            "email": "sabin.khanal.33@gmail.com",
                                            "password": "appleball",
                                            "full_name": "sabin khanal"
                                        }
                                    }
                                ]
                            },
                            "example": {
                                "email": "sabin.khanal.33@gmail.com",
                                "password": "appleball",
                                "full_name": "sabin khanal"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/auth/login": {
            "post": {
                "tags": ["Authentication"],
                "summary": "Login API",
                "description": "Helps user log in to the system.\r\n",
                "operationId": "LoginAPI",
                "parameters": [],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "allOf": [
                                    {
                                        "$ref": "#/components/schemas/LoginAPIRequest"
                                    },
                                    {
                                        "example": {
                                            "email": "sabin.khanal.33@gmail.com",
                                            "password": "appleball"
                                        }
                                    }
                                ]
                            },
                            "example": {
                                "email": "sabin.khanal.33@gmail.com",
                                "password": "appleball"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false,
                "security": []
            }
        },
        "/auth/token": {
            "post": {
                "tags": ["Authentication"],
                "summary": "Regenerate token using refresh token",
                "operationId": "regenerate_token",
                "parameters": [],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "allOf": [
                                    {
                                        "$ref": "#/components/schemas/RegenerateTokenRequest"
                                    },
                                    {
                                        "example": {
                                            "email": "sabin.khanal.33@gmail.com",
                                            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhYmluLmtoYW5hbC4zM0BnbWFpbC5jb20iLCJpYXQiOjE2Njk2MDIzOTgsImV4cCI6MTY2OTYzODM5OH0.ACo860pen0CJaJ1bpL3ZuuxJKQdf8It2fUqihMYjZRY"
                                        }
                                    }
                                ]
                            },
                            "example": {
                                "email": "sabin.khanal.33@gmail.com",
                                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhYmluLmtoYW5hbC4zM0BnbWFpbC5jb20iLCJpYXQiOjE2Njk2MDIzOTgsImV4cCI6MTY2OTYzODM5OH0.ACo860pen0CJaJ1bpL3ZuuxJKQdf8It2fUqihMYjZRY"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/users": {
            "get": {
                "tags": ["User Management"],
                "summary": "Fetch Users",
                "operationId": "FetchUsers",
                "parameters": [],
                "security": [
                    {
                        "bearer": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/uploads/image": {
            "post": {
                "tags": ["Uploads"],
                "summary": "Upload Image",
                "operationId": "UploadImage",
                "parameters": [],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "required": ["image"],
                                "type": "object",
                                "properties": {
                                    "image": {
                                        "type": "string",
                                        "format": "binary"
                                    }
                                }
                            }
                        }
                    },
                    "required": false
                },
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false,
                "security": [
                    {
                        "bearer": []
                    }
                ]
            }
        },
        "/": {
            "get": {
                "tags": ["Misc"],
                "summary": "Base API",
                "operationId": "BaseAPI",
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/uploads/4baacdd20e2199705a2f2749355098b5-time1.jpg": {
            "get": {
                "tags": ["Misc"],
                "summary": "Public Resource",
                "operationId": "PublicResource",
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        }
    },
    "components": {
        "schemas": {
            "AddPatientRequest": {
                "title": "Add Patient Request",
                "required": ["full_name", "email", "phone", "address", "date_of_birth",
                    "is_special_attention"],
                "type": "object",
                "properties": {
                    "full_name": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "phone": {
                        "type": "string"
                    },
                    "address": {
                        "type": "integer"
                    },
                    "date_of_birth": {
                        "type": "string"
                    },
                    "is_special_attention": {
                        "type": "string"
                    },
                    "avatar_filename": {
                        "type": "string"
                    },
                    "allergies": {
                        "type": "object"
                    }
                },
                "example": {
                    "full_name": "Ram Lakhan",
                    "email": "ak00313@gmail.com",
                    "phone": "9863180880",
                    "address": "Kathmandu",
                    "date_of_birth": "2022-11-01",
                    "is_special_attention": true,
                    "avatar_filename": "xxx.jpg"
                }
            },
            "UpdatePatientRequest": {
                "title": "Add Patient Request",
                "required": ["full_name", "email", "phone", "address", "date_of_birth",
                    "is_special_attention"],
                "type": "object",
                "properties": {
                    "full_name": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "phone": {
                        "type": "string"
                    },
                    "address": {
                        "type": "integer"
                    },
                    "date_of_birth": {
                        "type": "string"
                    },
                    "is_special_attention": {
                        "type": "string"
                    },
                    "avatar_filename": {
                        "type": "string"
                    },
                    "allergies": {
                        "type": "object"
                    }
                },
                "example": {
                    "full_name": "Ram Lakhan",
                    "email": "ak00313@gmail.com",
                    "phone": "9863180880",
                    "address": "Kathmandu",
                    "date_of_birth": "2022-11-01",
                    "is_special_attention": true,
                    "avatar_filename": "xxx.jpg"
                }
            },
            "SignupAPIRequest": {
                "title": "Signup API Request",
                "required": ["email", "password", "full_name"],
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    },
                    "full_name": {
                        "type": "string"
                    }
                },
                "example": {
                    "email": "sabin.khanal.33@gmail.com",
                    "password": "appleball",
                    "full_name": "sabin khanal"
                }
            },
            "RegenerateTokenRequest": {
                "title": "Regenerate Token Request",
                "required": ["email", "token"],
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string"
                    },
                    "token": {
                        "type": "string"
                    }
                },
                "example": {
                    "email": "sabin.khanal.33@gmail.com",
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhYmluLmtoYW5hbC4zM0BnbWFpbC5jb20iLCJpYXQiOjE2Njk2MDIzOTgsImV4cCI6MTY2OTYzODM5OH0.ACo860pen0CJaJ1bpL3ZuuxJKQdf8It2fUqihMYjZRY"
                }
            },
            "LoginAPIRequest": {
                "title": "Login API Request",
                "required": ["email", "password"],
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    }
                },
                "example": {
                    "email": "sabin.khanal.33@gmail.com",
                    "password": "appleball"
                }
            }
        },
        "securitySchemes": {
            "bearer": {
                "type": "http",
                "scheme": "bearer"
            }
        }
    },
    "security": [],
    "tags": [
        {
            "name": "Authentication"
        },
        {
            "name": "Patients",
            "description": "API endpoints for patient management"
        },
        {
            "name": "Misc",
            "description": ""
        },
        {
            "name": "Uploads",
            "description": ""
        }
    ]
}
